# -*- coding: utf-8 -*-
#
# Mapbender documentation build configuration file, created by
# sphinx-quickstart on Sun Jul  8 00:08:58 2012.
#
# This file is execfile()d with the current directory set to its containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

import sys
import os
import shlex
from sphinx.highlighting import lexers
from pygments.lexers.web import PhpLexer
from pygments.lexers.templates import TwigHtmlLexer
from pygments.lexers.templates import TwigLexer
from pygments.lexers.data import YamlLexer
from pygments.lexers.sql import PostgresLexer
from pygments.lexers.resource import ResourceLexer

# Symfony Extension Start
#sys.path.append(os.path.abspath('_exts'))

# enable highlighting for PHP code not between ``<?php ... ?>`` by default
lexers['php']      = PhpLexer(startinline=True, linenos=1)
lexers['twig']     = TwigHtmlLexer()
lexers['postgres'] = PostgresLexer()
lexers['yaml']     = YamlLexer()
lexers['resource'] = ResourceLexer()

# use PHP as the primary domain
primary_domain = 'php'
highlight_language = 'php'

# ...
# add the extensions to the list of extensions

# set url for API links
api_url = 'http://api.symfony.com/master/%s'
# Symfony Extension End

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#sys.path.insert(0, os.path.abspath('.'))

# -- Internationalization configuration ----------------------------------------
# -- Options for sphinx-intl example -------------------------------------------

locale_dirs = ['locale/']   # path is example but recommended.
gettext_compact = False     # optional.

# -- General configuration -----------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be extensions
# coming with Sphinx (named 'sphinx.ext.*') or your custom ones.
extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.todo',
    'sphinx.ext.coverage',
    'sphinxcontrib.phpdomain'
]

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix of source filenames.
source_suffix = '.rst'

# The encoding of source files.
#source_encoding = 'utf-8-sig'

# The master toctree document.
master_doc = 'index'

# General information about the project.
project = u'Mapbender'
copyright = u'2019, The Mapbender Team'

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
# The short X.Y version.
# Mapbender uses three digits.
version = '3.0.8'
# The full version, including alpha/beta/rc tags.
release = '3.0.8'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
language = None

# There are two options for replacing |today|: either, you set today to some
# non-false value, then it is used:
#today = ''
# Else, today_fmt is used as the format for a strftime call.
#today_fmt = '%B %d, %Y'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']

# The reST default role (used for this markup: `text`) to use for all documents.
#default_role = None

# If true, '()' will be appended to :func: etc. cross-reference text.
#add_function_parentheses = True

# If true, the current module name will be prepended to all description
# unit titles (such as .. function::).
#add_module_names = True

# If true, sectionauthor and moduleauthor directives will be shown in the
# output. They are ignored by default.
#show_authors = False

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'

# A list of ignored prefixes for module index sorting.
#modindex_common_prefix = []


# -- Options for HTML output ---------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#html_theme = 'mapbender'
html_theme = "sphinx_rtd_theme"

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
#html_theme_options = {}

# Add any paths that contain custom themes here, relative to this directory.
html_theme_path = ['_theme']

# The name for this set of Sphinx documents.  If None, it defaults to
# "<project> v<release> documentation".
html_title = 'Mapbender Documentation'

# A shorter title for the navigation bar.  Default is the same as html_title.
html_short_title = 'Mapbender Documentation'

# The name of an image file (relative to this directory) to place at the top
# of the sidebar.
html_logo = '_static/mapbender_logo.png'

# The name of an image file (within the static path) to use as favicon of the
# docs.  This file should be a Windows icon file (.ico) being 16x16 or 32x32
# pixels large.
html_favicon = '_static/mapbender3.ico'

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

# If not '', a 'Last updated on:' timestamp is inserted at every page bottom,
# using the given strftime format.
#html_last_updated_fmt = '%b %d, %Y'

# If true, SmartyPants will be used to convert quotes and dashes to
# typographically correct entities.
#html_use_smartypants = True

# Custom sidebar templates, maps document names to template names.
#html_sidebars = {}

# Additional templates that should be rendered to pages, maps page names to
# template names.
#html_additional_pages = {}

# If false, no module index is generated.
#html_domain_indices = True

# If false, no index is generated.
#html_use_index = True

# If true, the index is split into individual pages for each letter.
#html_split_index = False

# If true, links to the reST sources are added to the pages.
#html_show_sourcelink = True

# If true, "Created using Sphinx" is shown in the HTML footer. Default is True.
#html_show_sphinx = True

# If true, "(C) Copyright ..." is shown in the HTML footer. Default is True.
#html_show_copyright = True

# If true, an OpenSearch description file will be output, and all pages will
# contain a <link> tag referring to it.  The value of this option must be the
# base URL from which the finished HTML is served.
#html_use_opensearch = ''

# This is the file name suffix for HTML files (e.g. ".xhtml").
#html_file_suffix = None

# Output file base name for HTML help builder.
htmlhelp_basename = 'Mapbenderdoc'


# -- Options for LaTeX output --------------------------------------------------
# see: https://www.sphinx-doc.org/en/master/latex.html for settings

latex_engine = 'xelatex' # also possible lualatex, pdflatex, latex

_PREAMBLE = r"""
    \usepackage[T1]{fontenc}
    \usepackage[titles]{tocloft}
    \usepackage{textcomp}
    \inputencoding{utf8}
    \setmainfont{Ubuntu}
    \setsansfont{Ubuntu}
    \setmonofont{Ubuntu Mono}
"""

_PREAMPLE_PDFLATEX = """
    \DeclareUnicodeCharacter{25CF}{$\bullet$}
    \DeclareUnicodeCharacter{251C}{\mbox{\kern.23em
      \vrule height2.2exdepth1exwidth.4pt\vrule height2.2ptdepth-1.8ptwidth.23em}}
    \DeclareUnicodeCharacter{2500}{\mbox{\vrule height2.2ptdepth-1.8ptwidth.5em}}
    \DeclareUnicodeCharacter{2514}{\mbox{\kern.23em
      \vrule height2.2exdepth-1.8ptwidth.4pt\vrule height2.2ptdepth-1.8ptwidth.23em}}
"""

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    #'papersize': 'letterpaper',

    # The font size ('10pt', '11pt' or '12pt').
    #'pointsize': '10pt',

    # Additional stuff for the LaTeX preamble.
    'preamble': _PREAMBLE,

    'inputenc' : '\\usepackage[utf8]{inputenc}',
    'utf8extra': ''
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title, author, documentclass [howto/manual]).
latex_documents = [
    (
        'de/index',
        'Mapbender_de.tex',
        u'Mapbender  Dokumentation',
        u'Das Mapbender Team',
        'manual'
    ),
    (
        'en/index',
        'Mapbender_en.tex',
        u'Mapbender  Documentation',
        u'The Mapbender Team',
        'manual'
    ),
]

# The name of an image file (relative to this directory) to place at the top of
# the title page.
#latex_logo = None

# For "manual" documents, if this is true, then toplevel headings are parts,
# not chapters.
#latex_use_parts = False

# If true, show page references after internal links.
#latex_show_pagerefs = False

# If true, show URL addresses after external links.
#latex_show_urls = False

# Documents to append as an appendix to all manuals.
#latex_appendices = []

# If false, no module index is generated.
#latex_domain_indices = True


# -- Options for manual page output --------------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [
    ('index', 'mapbender', u'Mapbender Documentation', [u'The Mapbender Team'], 1)
]

# If true, show URL addresses after external links.
#man_show_urls = False


# -- Options for Texinfo output ------------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (
        'de/index',
        'Mapbender DE',
        u'Mapbender Dokumentation',
        u'Das Mapbender Team',
        'Mapbender',
        'Ein KartenCMS',
        'Miscellaneous'
    ),
    (
        'en/index',
        'Mapbender EN',
        u'Mapbender Documentation',
        u'The Mapbender Team',
        'Mapbender',
        'A mapclient CMS',
        'Miscellaneous'
    ),
]

# Documents to append as an appendix to all manuals.
#texinfo_appendices = []

# If false, no module index is generated.
#texinfo_domain_indices = True

# How to display URL addresses: 'footnote', 'no', or 'inline'.
#texinfo_show_urls = 'footnote'

# Override RTD_Theme CSS
# https://github.com/rtfd/sphinx_rtd_theme/issues/117
html_context = {
    'css_files': [
        '_static/theme_overrides.css',  # overrides for wide tables in RTD theme
    ],
    'display_github': True, # Add 'Edit on Github' link instead of 'View page source'
    'github_user': 'mapbender',
    'github_repo': 'mapbender-documentation',
    'github_version': 'master/'
}
